version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ".github/workflows: "
    reviewers: [jschaf]
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "go.mod: "
    reviewers: [jschaf]
    groups:
      go.mod:
        patterns: ["*"]
